export const cities = [
  '25 de Agosto',
  '25 de Mayo',
  'Abayubá',
  'Aceguá',
  'Achar',
  'Aiguá',
  'Albisu',
  'Algorta',
  'Andresito',
  'Área Rural',
  'Artigas',
  'Atlántida',
  'Balneario Iporá',
  'Baltasar Brum',
  'Barra de Carrasco',
  'Barrio Norte',
  'Belén',
  'Bella Unión',
  'Bellaco',
  'Bernabé Rivera',
  'Biassini',
  'Canelones',
  'Cardal',
  'Cardona',
  'Cardozo',
  'Carmelo',
  'Castillos',
  'Casupá',
  'Cerro Chato',
  'Cerro Colorado',
  'Cerro Pelado',
  'Chacras de Dolores',
  'Chamberlain',
  'Chuy',
  'Ciudad de la Costa',
  'Ciudad de Plata',
  'Clara',
  'Colón',
  'Colonia 18 de Julio',
  'Colonia de Sacramento',
  'Colonia Itapebí',
  'Colonia Nicolich',
  'Colonia Ofir',
  'Colonia Palma',
  'Constitución',
  'Cuchilla de Peralta',
  'Cuchilla del Ombú',
  'Curtina',
  'Dolores',
  'Durazno',
  'Ecilda Paullier',
  'Ejido de Treinta y Tres',
  'El Ombú',
  'Fernández',
  'Florida',
  'Fraile Muerto',
  'Fray Bentos',
  'Fray Marcos',
  'Garibaldi',
  'Gartenal',
  'General Borges',
  'General Enrique Martínez',
  'Grecco',
  'Gregorio Aznárez',
  'Guichón',
  'Hipódromo',
  'Illescas',
  'Isidoro Noblía',
  'Ismael Cortinas',
  'José Batlle y Ordóñez',
  'José Enrique Rodó',
  'José Ignacio',
  'José Pedro Varela',
  'Juan Lacaze',
  'La Barra',
  'La Casilla',
  'La Paloma',
  'La Paz',
  'La Pedrera',
  'La Pedrera',
  'Lago Merín',
  'Las Cañas',
  'Las Piedras',
  'Las Toscas',
  'Lascano',
  'Laureles',
  'Libertad',
  'Los Arrayanes',
  'Maldonado',
  'Mariscala',
  'Masoller',
  'Melo',
  'Menafra',
  'Mercedes',
  'Minas de Corrales',
  'Minas',
  'Montes Quintela',
  'Montevideo Rural',
  'Montevideo',
  'Nico Pérez',
  'Nueva Helvecia',
  'Nueva Palmira',
  'Nuevo Berlín',
  'Nuevo Paysandú',
  'Pajas Blancas',
  'Palmitas',
  'Pan de Azúcar',
  'Pando',
  'Paso Bonilla',
  'Paso Campamento',
  'Paso Carrasco',
  'Paso de los Mellizos',
  'Paso de toros',
  'Paso del Cerro',
  'Paysandú',
  'Piedra Sola',
  'Piedras Coloradas',
  'Pinares-Las Delicias',
  'Pirarajá',
  'Piriápolis',
  'Plácido Rosas',
  'Portezuelo',
  'Porvenir',
  'Pueblo de Barro',
  'Pueblo Lavalleja',
  'Punta de Cinco Sauces',
  'Punta del Este',
  'Puntas de Valdez',
  'Quebracho',
  'Rafael Perazza',
  'Rincón de Valentín',
  'Rincón del Bonete',
  'Río Branco',
  'Rivera',
  'Rodríguez',
  'Rosario',
  'Salto',
  'Sam Félix',
  'San Antonio',
  'San Carlos',
  'San Gregorio de Polanco',
  'San Javier',
  'San José de Mayo',
  'San Rafael-El placer',
  'Santa Clara de Olimar',
  'Santa Lucía',
  'Santa Teresa',
  'Santiago Vázquez',
  'Sarandí de Navarro',
  'Sarandí del Arapey',
  'Sarandí del Yí',
  'Sarandí Grande',
  'Sauce de Batoví',
  'Saucedo',
  'Sequeira',
  'Solís de Mataojo',
  'Tacuarembó',
  'Tambores',
  'Tambores',
  'Tarariras',
  'Termas del Daymán',
  'Tomás Gomensoro',
  'Tranqueras',
  'Treinta y Tres',
  'Trinidad',
  'Tupambaé',
  'Vergara',
  'Vichadero',
  'Villa Ansina',
  'Villa del Carmen',
  'Villa María',
  'Villa Sara',
  'Villa Soriano',
  'Young',
  'Zapicán',
];
